In [37]:
from transformers import BertTokenizer


tokenizer = BertTokenizer.from_pretrained("./protbert", do_lower_case=False)

# Your Antibody sequence
antiSeq= ['QSVLTQPPSASGTPGQRVTISCSGSSSNIGSNTVNWYQQLPGTAPKLLIYSNNQRPSGVPDRFSGSKSGTSASLAISGLQSEDEADYYCAAWDDSLNXXVFGGGTKLTVL','AIRMTQSPSSFSASTGDRVTITCRASQGISSYLAWYQQKPGKAPKLLIYAASTLQSGVPSRFSGSGSGTDFTLTISCLQSEDFATYYCQQYYSYPWTFGQGTKVEIK','DIQMTQSPSSVSASVGDRVTITCRASQDIKRWLAWFQQKPGKAPNLLIYSGSSLQSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQANSLPYTFGPGTKVDIK','EVQLVQSGAEVKKPGESLKISCKGSGYSFTTYWIGWVRQMPGKGLEWMGIIYPGDSDTRYSPSFQGQVTISADKSISTAYLQWSSLKASDTAMYYCARQGGYSYGQGGVDYWGRGTLVTVSS','QSVLTQPPSASGTPGQRVTISCSGSSSNIGSNTVNWYQQLPGTAPKLLIYSNNQRPSGVPDRFSGSKSGTSASLAISGLQSEDEADYYCAAWDDSLNGYVFGTGTKVTVL','DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKLLIYKASSLESGVPSRFSGSGSGTEFTLTISSLQPDDFATYYCQQYNSYSRTFGQGTKVEIK','QVQLVESGGGVVQPGRSLRLSCAASGFTFSSYGMHWVRQAPGKGLEWVAVASSAGSNKYHADSVKGRFTVSRDNSKSTLYLQMNSLRAEDTAVYYCAKTSCSGGSCYSDYWGQGTLVTVSS','QVQLVESGGGLVKPGGSLRLSCAASGFTFSDYYMSWIRQAPGKGLEWVSYISSSSSYTNYADSVKGRFTISRDNAKNSLYLQMNSLRAEDTAVYYCARXXXQWLXXDAFDIWGQGTMVTVSS']

antibody_sequence = []
# tokenize 
for s in antiSeq:
    spaced_antiSeq = ' '.join([char for char in s])
    antibody_sequence.append(tokenizer(spaced_antiSeq, truncation=True, max_length=512, padding=True))

antibody_sequence[0]

{'input_ids': [2, 18, 10, 8, 5, 15, 18, 16, 16, 10, 6, 10, 7, 15, 16, 7, 18, 13, 8, 15, 11, 10, 23, 10, 7, 10, 10, 10, 17, 11, 7, 10, 17, 15, 8, 17, 24, 20, 18, 18, 5, 16, 7, 15, 6, 16, 12, 5, 5, 11, 20, 10, 17, 17, 18, 13, 16, 10, 7, 8, 16, 14, 13, 19, 10, 7, 10, 12, 10, 7, 15, 10, 6, 10, 5, 6, 11, 10, 7, 5, 18, 10, 9, 14, 9, 6, 14, 20, 20, 23, 6, 6, 24, 14, 14, 10, 5, 17, 25, 25, 8, 19, 7, 7, 7, 15, 12, 5, 15, 8, 5, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [38]:
import torch
import ast
from model import AntibodyFormer
import os
from torch.utils.data import Dataset, DataLoader


device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = AntibodyFormer()

model.load_state_dict(torch.load('./model_save/model.ckpt', map_location=device))
model.eval()
model = model.to(device)
model

AntibodyFormer(
  (AntiFormer): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 256, padding_idx=0)
      (position_embeddings): Embedding(512, 256)
      (token_type_embeddings): Embedding(2, 256)
      (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=256, out_features=256, bias=True)
              (key): Linear(in_features=256, out_features=256, bias=True)
              (value): Linear(in_features=256, out_features=256, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=256, out_features=256, bias=True)
              (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affi

In [39]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
def bio_collate_fn(batch):

    input_ids = []
    attention_mask = []
    token_type_ids = []

    for ist in batch:
        id = ist['input_ids']
        mk = ist['attention_mask']
        ty = ist['token_type_ids']
        while len(id)<512:
            id.append(0)
        while len(mk)<512:
            mk.append(0)
        while len(ty)<512:
            ty.append(0)
        input_ids.append(torch.Tensor(id))
        attention_mask.append(torch.Tensor(mk))
        token_type_ids.append(torch.Tensor(ty))

    input_ids = torch.stack(input_ids).long()
    attention_mask = torch.stack(attention_mask).long()
    token_type_ids = torch.stack(token_type_ids).long()

    # knowledge graph
    num_channels = 1
    node_map = [input_ids.float() for _ in range(num_channels)]
    node_map = torch.stack(node_map)
    adjs = [torch.ones(len(batch), len(batch)) for _ in range(num_channels)]
    adjs = torch.stack(adjs)

    input_ids = input_ids.to(device)
    attention_mask = attention_mask.to(device)
    token_type_ids = token_type_ids.to(device)

    node_map = node_map.to(device)
    adjs =adjs.to(device)


    return input_ids, attention_mask, token_type_ids, node_map, adjs

input_ids, attention_mask, token_type_ids, node_map, adjs = bio_collate_fn(antibody_sequence)  # batch_size*seq_len

input_ids
node_map
adjs


tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]], device='cuda:0')

In [40]:

output_pobs = model(input_ids, attention_mask, token_type_ids, node_map, adjs)
sigmoid_output = torch.sigmoid(output_pobs)
sigmoid_output


tensor([[0.9968, 0.3332],
        [0.6614, 0.4745],
        [0.9822, 0.3774],
        [0.9096, 0.4288],
        [0.9967, 0.3338],
        [0.8361, 0.4468],
        [0.6311, 0.4826],
        [0.4238, 0.5073]], device='cuda:0', grad_fn=<SigmoidBackward0>)

In [41]:
pred = torch.argmax(sigmoid_output,dim=1)
pred

tensor([0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')

In [42]:
for seq in pred:
    if seq==0:
        print('low affinity')
    else:
        print('binder')

low affinity
low affinity
low affinity
low affinity
low affinity
low affinity
low affinity
binder
